# Generated by Django 4.1.7 on 2023-03-24 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
